apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:
  - secretName: mysql-credentials
    type: Opaque
    data:
    - objectName: mysql-root-password
      key: mysql-root-password
    - objectName: mysql-user
      key: mysql-user
    - objectName: mysql-password
      key: mysql-password
  parameters:
    objects: |
      - objectName: "mysql-credentials"
        objectType: "secretsmanager"
        objectVersion: "AWSCURRENT"
    region: "us-east-1" # Adjust to your region
